name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Remove conflicting containerd package
        continue-on-error: true
        run: |
          sudo apt-get remove -y containerd.io containerd || true
          sudo apt-get autoremove -y || true
          sudo apt-get clean

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      - name: Verify Docker Installation
        run: |
          docker --version
          docker-compose --version

      - name: Increase Docker permissions
        run: |
          sudo usermod -aG docker $USER
          sudo chmod 666 /var/run/docker.sock

      - name: Build and start containers
        run: |
          docker-compose up --build -d

      - name: List running containers
        run: |
          docker ps -a

      - name: Run API Tests
        continue-on-error: true
        run: |
          docker-compose exec -T fastapi_service pytest tests/ || true

      - name: Show logs if tests fail
        if: failure()
        run: |
          docker-compose logs

      - name: Cleanup containers
        run: |
          docker-compose down || true
