name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Fix containerd conflict
        run: |
          sudo apt-get remove -y containerd || true
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      - name: Build Docker Image
        run: |
          docker-compose -f docker-compose.yml up --build -d

      - name: Run API Tests
        run: |
          docker-compose exec -T api pytest tests/

      - name: Cleanup
        run: |
          docker-compose down
